### ISSUE TITLE
Search/Rank

### ISSUE THREAD

**Issue by ducvui2003** [ducvui2003/spring-boot-music-application#2]
# Task
## Search
- [ ] Lấy bài hát theo thể loại
- [ ] Lấy bài hát theo playlist
- [ ] Lấy bài hát theo nghệ sĩ
- [ ] Lấy bài hát theo lượt xem
## Rank
- [ ] Lấy danh sách playlist nghe gần đây
 - Dựa theo lịch sử nghe bài hát user nghe -> truy ra playlist đang được nghe nhiều (playlist này có thể của user hoặc là public)
- [ ] Lấy danh sách các thể loại (gerne) nổi bật
 - Tổng số lượt nghe của toàn bộ bài hát thuộc thể loại đó lớn
- [ ] Lấy danh sách các bài hát đang được nghe nhiều nhất
- [ ] Lấy danh sách artist nổi bật nhất 
 - Có bài hát đg được nghe nhiều nhất
 - Profile được người dùng yêu thích
- [ ] Lấy danh sách album có tổng số bài hát có lượt nghe lớn nhất
